### PR TITLE
report unknown when ubuntu version cannot be identified

### LINKED ISSUE #205: Make sure Ubuntu CPE reports correctly when the version isn't matched to an OS version
Example case was when we saw a banner like this.... "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-8"

I fixed the fingerprint for this in #204, but to reproduce this bug we just need to see something like "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-9" and it will improperly show up in the JSON output like this...

    "os_cpe": "o:canonical:ubuntu:#<SSHScan::OS::Ubuntu::Version:0x007f8c9e9741e0>",

### PR DESCRIPTION
**Pull request by agaurav77**
Should fix #205.

### CODE REVIEW

File: lib/ssh_scan/os/ubuntu.rb [hunk 1]
```diff
@@ -3,7 +3,11 @@ module OS
     class Ubuntu
       class Version
         def initialize(version_string)
-          @version_string = version_string
+          if version_string.nil?
+            @version_string = "unknown"
```
Comment (claudijd) [inline lib/ssh_scan/os/ubuntu.rb]: What if version_string was just nil rather than unknown?

I'm considering removing "unknown" references that have been a convention thus far because they don't follow CPE conventions.

File: spec/ssh_scan/banner/os/ubuntu_spec.rb [hunk 2]
```diff
@@ -238,6 +238,11 @@
         :ssh_lib_class => SSHScan::SSHLib::OpenSSH,
         :ssh_lib_version => "5.9p1",
       },
+      "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-9" => {
+        :os_class => SSHScan::OS::Ubuntu,
+        :os_version => "unknown",
```
Comment (claudijd) [inline spec/ssh_scan/banner/os/ubuntu_spec.rb]: Because a #to_s on a nil is "" that would be the switch here.

**Comment by claudijd** [comment]
Looks good, just a comment about phasing out the "unknown" convention.

File: lib/ssh_scan/os/ubuntu.rb (hunk 1 above)
Comment (agaurav77) [inline lib/ssh_scan/os/ubuntu.rb]: How about making the cpe "o:canonical:ubuntu" (without ":unknown") then?

**Comment by agaurav77** [comment]
@claudijd added another comment

File: lib/ssh_scan/os/ubuntu.rb (hunk 1 above)
Comment (claudijd) [inline lib/ssh_scan/os/ubuntu.rb]: yeah, that seems most logical.

Comment (agaurav77) [inline lib/ssh_scan/os/ubuntu.rb]: Done!
